### ISSUE TITLE
config:get show default config.xml value

### ISSUE THREAD

**Issue by rafaelstz** [netz98/n98-magerun2#1025] opened 2022-08-09 17:58 UTC
## Current Implementation

The current config:get doesn't show the default value from the config.xml if it's not in the database.

## Suggested Enhancement

Check the default value in case there's no value found via DB.
https://github.com/netz98/n98-magerun2/blob/develop/src/N98/Magento/Command/Config/Store/GetCommand.php#L128

This alias function does this:

```
function m2-config-get () {
  bin/mageru2 dev:con "\$di->create(\Magento\Framework\App\Config\ScopeConfigInterface::class)->getValue('$1');exit" | grep '=>'
}
```

## Expected Benefits

![image](https://user-images.githubusercontent.com/610598/183725501-0182a4a3-36a0-40b9-ac6d-99741020c620.png)

**Comment by convenient** [comment] 2022-10-12 13:36
Possibly a subset of https://github.com/netz98/n98-magerun2/issues/712

>It would be neat if we could have config:store:get read default.xml, config.php, and env.php appropriately.

**Comment by cmuench** [comment] 2022-10-13 06:35
@rafaelstz Duplicate of #712

**Closed by cmuench** 2022-10-13 06:35 UTC
Labels: enhancement
