### ISSUE TITLE
Integration in Nix - upload build asset (phar) to Github release?

### ISSUE THREAD

**Issue by drupol** [netz98/n98-magerun2#1098] opened 2023-01-23 12:28 UTC
Hello,

I'm Pol, a PHP maintainer in the NixOS community.

Today @fballiano has open a [PR](https://github.com/NixOS/nixpkgs/pull/212249) to include Magerun 1 and 2 in Nix.

Since I do not know anything about Magento and its tooling, I was wondering if it would be possible to download the phar directly from the Github release, just like `php-cs-fixer` and many other tools are doing (https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/releases)

Attaching the phar could be automatic through a simple Github action upon tag. I see that it would not require a lot of work since [you already have a workflow](https://github.com/netz98/n98-magerun2/blob/develop/.github/workflows/phar_build_and_update.yml) building and testing the phar.

Having a clear and open process on how the phar is built on Github would clear out any security concerns and also would be automatically updated in Nix by an internal automated process. 

Let me know what you think about this.

Thanks.

**Comment by drupol** [comment] 2023-01-23 13:43
> @drupol: Thank you for your interest and reaching out. Christian can likely answer with more detail, n98-magerun and n98-magerun2 has signed phar file releases on https://files.magerun.net/ . We once had the phar file build reproducible, so that connecting the dots with git revisions and object / tree hashes and the phar build scripts should not be an issue. There is also a distribution via PHIVE (phar.io).

Cool, good news :)

What worries me, as a total newcomer in the Magento world is how those phar are built. Nothing is currently linking the sources to the phar provided on the website.
Having those phar built on Github and attached to a release tag would definitely clear those concerns.

> And just curious, wouldn't it be better for Nix to build the phar from sources? Better than transparency is control and also the nix build has some nice properties I'd also like to a look for making use of, that is with a different phar building project called [pipelines](https://github.com/ktomk/pipelines). I'm not a NixOS user much, but have been playing with the Nix Package Manager on Linux. In pipelines we have Microsoft Github asset releases there, but the remote build for that is currently broken and I want to have the whole build out of the castle in the sky finally after running into cloud weather in remote CI systems over the years and I personally don't want to dependend on Github for the real build and release. I'm currently switching to over to deploy the assets from local and could connect such a pipeline with nixpkgs directly.

I'm all in favor of that. However, there is currently no "standardized" nor "easy" process to do so. To ensure reproducibility, all the inputs must be provided to the builder. In this case, we need `composer` to download dependencies... and while this might introduce entrooy, network is neither not available while building a package, so we are blocked right now. We don't have much options. Solutions like [svanderburg/composer2nix](https://github.com/svanderburg/composer2nix) are working most of the time, but not for all the packages sadly. I hope to have some time one day to dedicate more resource into having a proper way to do that.

> Christian must say what for Magerung the thoughts are, I'm just chiming in as having done reproducible phar builds for quite some time also across PHP versions and I'm also interested in packaging PHP utils in NixPkg just had not the time to ask for that earlier. So I would be interested especially on how to package transparently directly with NixPkgs from PHP sources, including the phar build itself (no idea if the phar is technically necessary, IIRC I could just run a shell.nix for my utility, but I'd love to have the practice for the reproducible phar build anyway).

If you want to experiment you could start by doing what I did with PHPStan [here](https://github.com/loophp/nix-phpstan), you can run the bleeding edge version of it by just doing: `nix run github:loophp/nix-phpstan -- analyze src/` nothing else, nothing more. Have a look at the repo to see how I did, it might give you some fresh ideas.

**Comment by ktomk** [comment] 2023-01-23 14:11
> Solutions like [svanderburg/composer2nix](https://github.com/svanderburg/composer2nix) are working most of the time

Have looked at it ca. six months ago, which must not mean I've understood much. Technically the phar already contains the vendor folder, given having a .lock file, it is not guaranteed to work, but mostly does (we practiced a lot of offline building incl. composer with pipelines). But its not ideal in terms of a self-contained build, and only that one is transparent IMHO.

What I did not understood is how it is possible to use PHP libraries directly (like as packages) in NixPkg so that a utility can depend on them but must not ship with everything. Also if it's possible to allow a broader set of the PHP executable, I understood it that it was the specific version to aim for but I might have not understood it well.

For a reproducible release in git, most straight forward to me seems to commit the vendor folder. That would also solve the problem having it as intermediate build target that is available offline only if the composer cache has it. It is also easier to reproduce (albeit if I got it right in Nix build it is that the first green one is the winner and there would be no re-build, so this would be effectively "committing" the vendor folder after building the vendor subtree or the phar archive.

**Comment by fballiano** [comment] 2023-01-23 14:27
@ktomk at openmage we have a release builder workflow that runs the composer install, creates a tarball (in your case it would be a phar) and adds it to the release itself:
- https://github.com/OpenMage/magento-lts/blob/1.9.4.x/.github/workflows/release.yml
- a test run https://github.com/fballiano/openmage/releases/tag/v20.test.5 (it's on my fork since I worked on the release builder and it's still not in production for openmage, although alread merged)

hope it helps with something :-)

**Comment by fballiano** [comment] 2023-01-23 16:24
I've copied openmage's release builder and modified for magerun here: https://github.com/fballiano/n98-magerun/blob/develop/.github/workflows/release.yml

for some reason attaching the phar to the github release (the last step) doesn't work, weird since it's the same code we use in openmage

**Comment by drupol** [comment] 2023-01-23 20:48
> I've copied openmage's release builder and modified for magerun here: https://github.com/fballiano/n98-magerun/blob/develop/.github/workflows/release.yml

Try to open a pull request against **your** repo instead of upstream's and see if it builds.

**Comment by fballiano** [comment] 2023-01-23 20:54
The release I’ve linked it’s already in my repo, that’s precisely how i developed the openmage’s one

**Comment by ktomk** [comment] 2023-01-23 21:02
hmm, I'm clueless in that regard then. however - for pushing things a bit here and there - what about a workflow trigger on a tag instead a release and then build from that tag. the artifact publishing on the releases may not work at the end, however it is also possible to have artifacts for the build iteration. IIRC in pipelines I keep them one day (two actually) so it cleans up afterwards fine. it also goes back and forth, e.g. to collect all artifacts of the workflow and compare that hashsums of the phar do match (or they diverge) - collect - so spotting cracks in the matrix. https://github.com/ktomk/pipelines/blob/master/.github/workflows/ci.yml#L118-L123

**Comment by drupol** [comment] 2023-01-23 21:13
I also made some tests: https://github.com/drupol/n98-magerun/actions/runs/3990564606/jobs/6844358105
With this [workflow](https://github.com/drupol/n98-magerun/blob/develop/.github/workflows/release.yml), right now it's unable to publish the release for an unrelated issue. I need to investigate.

**Comment by drupol** [comment] 2023-01-23 21:27
First successful test: https://github.com/drupol/n98-magerun/actions/runs/3990688011/jobs/6844628044
Phar: https://github.com/drupol/n98-magerun/releases/tag/test7

**Comment by drupol** [comment] 2023-01-24 07:29
@ktomk WDYT ? I can submit the PR for both repository if you're ok with that ?

**Comment by ktomk** [comment] 2023-01-24 07:38
@drupol: Sure, please file a PR.

**Comment by ktomk** [comment] 2023-01-24 07:39
@drupol and thinking, can you create an issue beforehand in the magerun 1 github? so we have an issue for documentation.

**Comment by drupol** [comment] 2023-01-24 07:41
sure, will do.

**Comment by drupol** [comment] 2023-01-24 07:51
Both PR/issues are done, let me know if there is something else to do.

**Closed** 2023-01-24 12:11 UTC
Labels: question
