### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Twig_Loader_Filesystem' not found in phar:///usr/local/bin/n98-magerun2/src/N98/Util/Template/Twig.php:23

### ISSUE THREAD

**Issue by arjenbruinning** [netz98/n98-magerun2#854] opened 2021-11-17 21:47 UTC
I try to run magerun2 sys:info. But I get an error:

PHP Fatal error:  Uncaught Error: Class 'Twig_Loader_Filesystem' not found in phar:///usr/local/bin/n98-magerun2/src/N98/Util/Template/Twig.php:23
Stack trace:
#0 phar:///usr/local/bin/n98-magerun2/src/N98/Util/Console/Helper/TwigHelper.php(27): N98\Util\Template\Twig->__construct(Array)
#1 phar:///usr/local/bin/n98-magerun2/src/N98/Magento/Application.php(608): N98\Util\Console\Helper\TwigHelper->__construct(Array)
#2 phar:///usr/local/bin/n98-magerun2/src/N98/Magento/Application.php(403): N98\Magento\Application->registerHelpers()
#3 phar:///usr/local/bin/n98-magerun2/src/N98/Magento/Application.php(315): N98\Magento\Application->init(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /usr/local/bin/n98-magerun2(8): N98\Magento\Application->run()
#5 {main}
  thrown in phar:///usr/local/bin/n98-magerun2/src/N98/Util/Template/Twig.php on line 23

My current version of Magento is 2.4.2 and PHOP version 7.3.

Does anybody have a clue what goes wrong and how I can fix it?

**Comment by cmuench** [comment] 2021-11-18 11:58
@arjenbruinning Could it be that you are using a very old n98-magerun2 version?
Can you try to update n98-magerun2?

**Comment by cmuench** [comment] 2021-11-18 13:02
@arjenbruinning I installed a fresh Magento CE 2.4.2 with PHP 7.3 and cannot reproduce the issue.

**Comment by cmuench** [comment] 2021-11-30 00:06
@arjenbruinning I updated the Twig dependency to v3 in develop branch. This will be released as v4.8.0 this week. Feel free to re-open the issue if it's not fixed.
Can still not produce the issue on my side.

**Closed by cmuench** 2021-11-30 00:06 UTC
