### ISSUE TITLE
During update - actual filesize mismatch on file "vendor/symfony/debug/Exception/FatalThrowableError.php"

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun2#407] opened 2018-11-07 08:30 UTC
Updating to version 2.3.1.
	Downloading (100%)Successfully updated n98-magerun2
	PHP Warning:  include(phar:///usr/local/bin/n98-magerun2/vendor/composer/../../src/N98/Util/Markdown/VersionFilePrinter.php): failed to open stream: phar error: internal corruption of phar "/usr/local/bin/n98-magerun2" (actual filesize mismatch on file "src/N98/Util/Markdown/VersionFilePrinter.php") in phar:///usr/local/bin/n98-magerun2/vendor/composer/ClassLoader.php on line 444
	PHP Warning:  include(): Failed opening 'phar:///usr/local/bin/n98-magerun2/vendor/composer/../../src/N98/Util/Markdown/VersionFilePrinter.php' for inclusion (include_path='.:/usr/share/php') in phar:///usr/local/bin/n98-magerun2/vendor/composer/ClassLoader.php on line 444
	PHP Warning:  include(phar:///usr/local/bin/n98-magerun2/vendor/composer/../symfony/debug/Exception/FatalThrowableError.php): failed to open stream: phar error: internal corruption of phar "/usr/local/bin/n98-magerun2" (actual filesize mismatch on file "vendor/symfony/debug/Exception/FatalThrowableError.php") in phar:///usr/local/bin/n98-magerun2/vendor/composer/ClassLoader.php on line 444
	PHP Warning:  include(): Failed opening 'phar:///usr/local/bin/n98-magerun2/vendor/composer/../symfony/debug/Exception/FatalThrowableError.php' for inclusion (include_path='.:/usr/share/php') in phar:///usr/local/bin/n98-magerun2/vendor/composer/ClassLoader.php on line 444
	PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Debug\Exception\FatalThrowableError' not found in phar:///usr/local/bin/n98-magerun2/vendor/symfony/console/Application.php:869
	Stack trace:
	#0 phar:///usr/local/bin/n98-magerun2/vendor/symfony/console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(N98\Magento\Command\SelfUpdateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#1 phar:///usr/local/bin/n98-magerun2/src/N98/Magento/Application.php(538): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#2 phar:///usr/local/bin/n98-magerun2/vendor/symfony/console/Application.php(117): N98\Magento\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#3 phar:///usr/local/bin/n98-magerun2/src/N98/Magento/Application.php(576): Symfony\Component\Console\Ap in phar:///usr/local/bin/n98-magerun2/vendor/symfony/console/Application.php on line 869

**Comment by cmuench** [comment] 2018-11-07 20:58
Confirmed. This occures after the update because the phar file which is currently running in the memory is already replaced on disk.
After that the autoloading is not working.
I will provide a patch.

**Comment by cmuench** [comment] 2018-11-07 21:01
Fixed in develop.

**Comment by cmuench** [comment] 2018-11-07 21:02
Hint: Problem is already in v2.3.0.

**Closed** 2018-11-17 18:08 UTC
Labels: bug
