### ISSUE TITLE
Magento 2.3.2 deploy:mode:set development

### ISSUE THREAD

**Issue by albertlensen** [netz98/n98-magerun2#479] opened 2019-07-02 14:47 UTC
running n98-magerun2 after installing magento 2.3.2 via composer gave me the following error: 
The mode can't be switched to "development".

```
#0 /var/www/html/magento-dev/vendor/symfony/console/Command/Command.php(255): Magento\Deploy\Console\Command\SetModeCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/html/magento-dev/vendor/magento/framework/Interception/Interceptor.php(58): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/magento-dev/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Deploy\Console\Command\SetModeCommand\Interceptor->___callParent('run', Array)
#3 /var/www/html/magento-dev/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Deploy\Console\Command\SetModeCommand\Interceptor->Magento\Framework\Interception\{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/magento-dev/generated/code/Magento/Deploy/Console/Command/SetModeCommand/Interceptor.php(104): Magento\Deploy\Console\Command\SetModeCommand\Interceptor->___callPlugins('run', Array, Array)
#5 phar:///home/albert/Scripts/n98-magerun2.phar/src/N98/Magento/Application.php(752): Magento\Deploy\Console\Command\SetModeCommand\Interceptor->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///home/albert/Scripts/n98-magerun2.phar/vendor/symfony/console/Application.php(185): N98\Magento\Application->doRunCommand(Object(Magento\Deploy\Console\Command\SetModeCommand\Interceptor), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///home/albert/Scripts/n98-magerun2.phar/src/N98/Magento/Application.php(237): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///home/albert/Scripts/n98-magerun2.phar/vendor/symfony/console/Application.php(117): N98\Magento\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///home/albert/Scripts/n98-magerun2.phar/src/N98/Magento/Application.php(327): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/albert/Scripts/n98-magerun2.phar(8): N98\Magento\Application->run()
#11 {main}
```

Via bin/magento it was successful.

**Comment by ktomk** [comment] 2019-07-06 22:10
@albertlensen can you add (by editing your original report) the command that triggers this? I'd like to better understand why it's not yet covered by the Travis build.

**Comment by cmuench** [comment] 2019-07-07 11:12
@albertlensen Did you call

`n98-magerun2.phar deploy:mode:set development` (which is wrong)
or
`n98-magerun2.phar deploy:mode:set developer` (correct)

At the moment I am not able to reproduce the problem.

**Comment by albertlensen** [comment] 2019-07-08 11:25
I don't know where my head was at, but looking in the history I apparently typed 'development' when using n98-magerun2, but 'developer' using bin/magento. And seemingly reused the same erroneous command with the verbose option(-v). When it gave a stack trace I assumed it was a bug. 

The correct command gave no problem. The error message can probably be improved upon by stating that the wrong mode does not exist instead of 'can't be switched' and not throw a stack trace, but I think that is part of Magento itself. 

Sorry for the inconvenience.

**Comment by cmuench** [comment] 2019-07-08 12:07
@albertlensen no worry. I close the issue.

**Closed by cmuench** 2019-07-08 12:07 UTC
Labels: bug, needs investigation
