### ISSUE TITLE
./n98-magerun2.phar fails silently

### ISSUE THREAD

**Issue by DeepakNatraj** [netz98/n98-magerun2#907] opened 2021-12-24 15:35 UTC
## Describe the bug

All commands except `n98-magerun2 -vvv` prints nothing.
When i try `./n98-magerun2.phar -vvv` it prints out
```
Load dist config
Search for Magento in folder pub
Search for Magento in folder /Applications/MAMP/htdocs/magentoapp
Found Magento  v2  in folder /Applications/MAMP/htdocs/magentoapp
Load dist config
```

But except this all other commands fails silently. Neither error nor some result is displayed.
Eg: `n98-magerun2.phar --version` or `n98-magerun2.phar install`

## Steps to reproduce the issue
Installed n98-magerun2 using the steps in doc
```
$ curl -O https://files.magerun.net/n98-magerun2.phar
$ shasum -a256 n98-magerun2.phar
```

Tried running it inside a magento application directory.

## Technical details

- Host Machine OS (Mac Monterey)
- PHP version 7.4.12
- Compose version 2.1.14

## Additional context
My Phar configuration in `php.ini` is
```
[Phar]
; http://php.net/phar.readonly
;phar.readonly = On

; http://php.net/phar.require-hash
;phar.require_hash = On

;phar.cache_list =
```

**Comment by ktomk** [comment] 2021-12-25 12:56
What version of Magerun2 is that? And if you can compare: What version did you know worked previously?

**Comment by DeepakNatraj** [comment] 2021-12-25 13:11
It's 4.9.0. I'm pretty new to php, so I've not worked on it before.

**Comment by ktomk** [comment] 2021-12-25 13:39
> It's 4.9.0. I'm pretty new to php, so I've not worked on it before.

Okay, so would it be right so say, this is on first-time use?

It somehow looks like the installation has gone bonkers. I have no apple system at hand to reproduce, and also not that many trouble-shooting tips for starters.

Let's try this first:

Could you please report the exit status/code for both commands? In shell it should be from the following two commands:

~~~
n98-magerun2 -vvv; echo $?
~~~
and
~~~
./n98-magerun2.phar -vvv; echo $?
~~~

Please provide the output of each of those.

**Comment by DeepakNatraj** [comment] 2021-12-25 14:10
Thanks. I'm not sure if its because of my previous n98-magerun2.phar file. I downloaded again from https://files.magerun.net/n98-magerun2.phar using browser and it worked.
`./n98-magerun2.phar --version` - `n98-magerun2 4.9.1 by netz98 GmbH`
But the version now is `4.9.1`.

It's working anyways. Thanks a lot.

**Comment by ktomk** [comment] 2021-12-25 14:31
This sounds good and as-if the previous installation was incomplete. I'll close the issue, if it is not "working anyways", just continue here and we can re-open it.

**Closed by ktomk** 2021-12-25 14:31 UTC
Labels: bug, support
