### ISSUE TITLE
N98-Magerun2 stops working when Magento has Twig installed, Twig versions 2.0 and above.

### ISSUE THREAD

**Issue by dannydamsky** [netz98/n98-magerun2#535] opened 2020-03-26 14:29 UTC
Steps to reproduce:

1. add "twig/twig": "~3.0" to composer.json in Magento 2
2. composer update
3. run ./n98-magerun2.phar in the application folder.

Expected result: n98-magerun2 runs as usual.
Actual Result: n98-magerun2 throws an exception.

**Comment by cmuench** [comment] 2020-03-26 16:09
@dannydamsky can you add the exception to the issue?

**Comment by dannydamsky** [comment] 2020-03-26 18:09
@cmuench 

P Fatal error:  Uncaught Error: Class 'Twig_Loader_Filesystem' not found in phar:///usr/bin/n98-magerun2.phar/src/N98/Util/Template/Twig.php:27
Stack trace:
#0 phar:///usr/bin/n98-magerun2.phar/src/N98/Util/Console/Helper/TwigHelper.php(29): N98\Util\Template\Twig->__construct(Array)
#1 phar:///usr/bin/n98-magerun2.phar/src/N98/Magento/Application.php(594): N98\Util\Console\Helper\TwigHelper->__construct(Array)
#2 phar:///usr/bin/n98-magerun2.phar/src/N98/Magento/Application.php(405): N98\Magento\Application->registerHelpers()
#3 phar:///usr/bin/n98-magerun2.phar/src/N98/Magento/Application.php(317): N98\Magento\Application->init(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /usr/bin/n98-magerun2.phar(8): N98\Magento\Application->run()
#5 {main}
  thrown in phar:///usr/bin/n98-magerun2.phar/src/N98/Util/Template/Twig.php on line 27

Fatal error: Uncaught Error: Class 'Twig_Loader_Filesystem' not found in phar:///usr/bin/n98-magerun2.phar/src/N98/Util/Template/Twig.php:27
Stack trace:
#0 phar:///usr/bin/n98-magerun2.phar/src/N98/Util/Console/Helper/TwigHelper.php(29): N98\Util\Template\Twig->__construct(Array)
#1 phar:///usr/bin/n98-magerun2.phar/src/N98/Magento/Application.php(594): N98\Util\Console\Helper\TwigHelper->__construct(Array)
#2 phar:///usr/bin/n98-magerun2.phar/src/N98/Magento/Application.php(405): N98\Magento\Application->registerHelpers()
#3 phar:///usr/bin/n98-magerun2.phar/src/N98/Magento/Application.php(317): N98\Magento\Application->init(Array, Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /usr/bin/n98-magerun2.phar(8): N98\Magento\Application->run()
#5 {main}
  thrown in phar:///usr/bin/n98-magerun2.phar/src/N98/Util/Template/Twig.php on line 27

**Comment by cmuench** [comment] 2020-03-29 14:09
@dannydamsky I was able to reproduce the issue and did some tests with twig 2 and twig 3 in a Magento installation.

I can upgrade the n98-magerun2 twig dependency to 2.0 and change the internal template loading. So the tool is still compatible for all users which have not installed twig as shop dependency.

It is currently not possible to update my depdency to twig 3.0 because we officially support PHP 7.2 for the next months.

With the proposed change the n98-magerun2 tool is running again if twig 3.0 is installed as Magento shop dependency. That's good.
If twig 3.0 is intalled, the n98-magerun2 command which depend on twig (like dev:module:create) cannot be used. Other commands work well.

I will merge that changes in develop branch if build is OK. Then you can test the change on your system by using the development version.

**Comment by dannydamsky** [comment] 2020-03-29 14:13
Okay, I will test it as soon as it's available.
Thanks!

**Comment by cmuench** [comment] 2020-03-29 14:17
@dannydamsky It's available in some minutes. Build is "green".

**Comment by cmuench** [comment] 2020-04-03 11:48
I close the issue.

**Closed by cmuench** 2020-04-03 11:48 UTC
