### ISSUE TITLE
cache:flush command do not dispatch the `adminhtml_cache_flush_all` event

### ISSUE THREAD

**Issue by viktorsteinwand** [netz98/n98-magerun2#263] opened 2016-12-28 18:02 UTC
If performing the `cache:flush` command, the expectation is, that the event like `adminhtml_cache_flush_all` or something similar will be dispatched. See https://github.com/netz98/n98-magerun2/blob/master/src/N98/Magento/Command/Cache/FlushCommand.php#L23

Please observe also the original Magento 2 cache flush command source: https://github.com/magento/magento2/blob/develop/app/code/Magento/Backend/Console/Command/CacheFlushCommand.php#L32

Thanks

**Comment by viktorsteinwand** [comment] 2017-01-02 08:44
Thanks Tom Klingenberg!

**Comment by tkn98** [comment] 2017-01-02 09:37
Thank you for the report! Let us know in case this does not work as intended:

We believe that the bug reported is fixed in the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.

**Closed by tkn98** 2017-01-02 09:37 UTC
Labels: enhancement
