### ISSUE TITLE
"Undefined index: host" error when running db:import

### ISSUE THREAD

**Issue by JosephLeedy** [netz98/n98-magerun2#882] opened 2021-11-29 23:02 UTC
## Describe the bug

When running `n98-magerun2 db:import`, I receive the following error:

>In ErrorHandler.php line 61:
>Notice: Undefined index: host in phar:///usr/local/bin/n98-magerun2/src/N98/Util/Console/Helper/DatabaseHelper.php on line 129

## Expected behaviour

I expected the database backup to be imported.

## Steps to reproduce the issue

1. Export a database backup with `n98-magerun2 db:dump`
1. Import the backup with `n98-magerun2 db:import`

## Technical details

- n98-magerun2 4.7.0
- macOS Big Sur 11.6.0
- PHP 7.4.26
- Adobe Commerce 2.4.3-p1
- MariaDB 10.4.22

## Possible Fix

N/A

## Additional context

N/A

**Comment by cmuench** [comment] 2021-11-29 23:09
@JosephLeedy Hi Joseph,
which version n98-magerun2 are you using?

**Comment by JosephLeedy** [comment] 2021-11-29 23:11
Apologies, I forgot to include that. I'm using version 4.7.0. Thanks!

**Comment by cmuench** [comment] 2021-11-29 23:18
@JosephLeedy No worry. Thought you are testing the beta version. I will try to release a new version 4.8.0 this week.
Coincidentally I merged a PR today, which modifies the DatabaseHelper. But it's not related. Seems that a simple isset is missing.
It the issue is not super critical for you, then I can release the fix with v4.8.0.

**Comment by JosephLeedy** [comment] 2021-11-29 23:20
I can work around it, thanks. I also get that error when I run ` n98-magerun2 db:add-default-authorization-entries`.

**Comment by cmuench** [comment] 2021-11-29 23:21
Could be. The DatabaseHelper is used in several DB commands.

**Comment by cmuench** [comment] 2021-11-29 23:47
@JosephLeedy I added a possible fix. If you like to test then you can update to dev build version which is also the RC1 for v4.8.0.
`n98-magerun2.phar self-update --unstable`

**Closed** 2021-12-06 10:28 UTC
Labels: bug

**Comment by JosephLeedy** [comment] 2021-12-06 15:02
Thanks! I haven't had time to test as I've been busy prepping for the holidays.

**Comment by cmuench** [comment] 2021-12-06 16:42
@JosephLeedy No worry. If there are still problems, just re-open this issue here.
