### ISSUE TITLE
"Area code is not set" launching a CLI Command

### ISSUE THREAD

**Issue by fabianaromagnoli** [netz98/n98-magerun2#448] opened 2019-04-02 09:57 UTC
**Summary**
I created a simple CLI command that, using product collection, loads all simple products that have a special price. If I launch the command using bin/magento, it works as expected, if I launch it with n98-magerun2, I get the "Area code is not set" exception

**Environment**
* PHP 7.1
* Magento EE 2.2.5
* n98-magerun2 3.0.7

**Steps to reproduce**
* Create a command with this code:

```
<?php
declare(strict_types=1);

namespace Webgriffe\Catalog\Console\Command\Product;

use Magento\Catalog\Model\ResourceModel\Product\CollectionFactory;
use Magento\Framework\App\Area;
use Magento\Framework\App\State;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class PopulateOffersAttribute extends Command
{
    /**
     * @var State
     */
    private $state;
    /**
     * @var CollectionFactory
     */
    private $productCollectionFactory;

    public function __construct(
        State $state,
        CollectionFactory $productCollectionFactory
    ) {
        parent::__construct();
        $this->state = $state;
        $this->productCollectionFactory = $productCollectionFactory;
    }

    protected function configure()
    {
        $this
            ->setName('webgriffe:test-command')
            ->setDescription(
                'Loads all simpel products with a special price'
            );
    }


    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return int|void|null
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    // phpcs:ignore Generic.CodeAnalysis.UnusedFunctionParameter
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->state->setAreaCode(Area::AREA_ADMINHTML);

        $productCollection = $this->productCollectionFactory->create();
        $productCollection
            ->addFieldToFilter('type_id', 'simple')
            ->addAttributeToFilter('special_price', ['notnull' => true]);
        $output->writeln(
            sprintf('Found %s simple products with special price', $productCollection->getSize())
        );
    }
}
```
* Launch it with bin/magento: `bin/magento webgriffe:test-command`. It works as expected:
<img width="491" alt="binmagento" src="https://user-images.githubusercontent.com/23638004/55392977-9eac4700-553c-11e9-99fc-8aae69c58ce7.png">

* Launch it with n98-magerun2: `n98-magerun2.phar webgriffe:test-command`, and you will see the LocalizedException with "Area code not set" message.

<img width="514" alt="n98" src="https://user-images.githubusercontent.com/23638004/55393177-0bbfdc80-553d-11e9-963c-533976c6f4b4.png">

**Other info**
* The line that causes the exception is line 57 
(`->addAttributeToFilter('special_price', ['notnull' => true]);`).  If I don't add the special_price filter, the  command works both with bin/magento and n98-magerun2
* The first line of the execute method is a setAreaCode instruction. Without it, I get exception both with n98-magerun2 and bin/magento, but in this case I have two exceptions: Magento\Framework\Exception\SessionException and Magento\Framework\Exception\LocalizedException:

<img width="527" alt="exceptions" src="https://user-images.githubusercontent.com/23638004/55393577-cea81a00-553d-11e9-9095-673529edb49e.png">

If I set the Area Code at the beginning of the execute method, both exceptions disappear using bin/magento, while I keep getting LocalizedException using n98-magerun2

**Comment by rickschippers** [comment] 2019-04-02 14:47
I have quite a few issues when running custom built cli commands using magerun 3.x. While they used to run fine on magerun 2.x with magento 2.2. The magento binary still runs them fine on 2.3.

On of the issues I've been running into is exactly the same as you have here. As soon as you start working with product repositories you get this error. This same issue happened with magerun internal commands. See here: https://github.com/netz98/n98-magerun2/pull/409

Applying the same hack in your own cli command: add `@session_start` somewhere in the beginning of the cli command's execute method fixes this specific issue. 

But besides this issue - I ran into a lot more issues when saving categories/products etc. I haven't had the time to check them thoroughly, so for now I just switched my custom commands to run with the magento binary.

**Comment by wojtekn** [comment] 2019-04-12 10:58
I also spot this issue, it was hidden deeply in the stack trace, but I was able to reproduce it using latest n98 with vanilla 2.3 using following CLI command::

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->state->setAreaCode(Area::AREA_FRONTEND);

        $om = \Magento\Framework\App\ObjectManager::getInstance();

        $state = $om->get('Magento\Framework\App\State');

        /** @var \Magento\Framework\App\State $state */
        var_dump($state->getAreaCode());
    }

And result:

    $ mage wojtek:test:test
    /Volumes/Sites/magento2/app/code/Wojtekn/Test/Console/TestCommand.php:63:
    vstring(8) "frontend"
    $ n98 wojtek:test:test                                                
    [Magento\Framework\Exception\LocalizedException]  
    Area code is not set

@rickschippers this problem can pop out when the session is started by CLI, but this part is being fixed in Magento 2.3.1:

**Comment by cmuench** [comment] 2019-04-16 15:59
The problem is in the `\Magento\Framework\Session\SidResolver::getSid` which is called by plugin. We added a solution for the n98-magerun commands. I am not sure how we can fix that.

**Comment by cmuench** [comment] 2019-12-29 14:52
@fabianaromagnoli 
I installed your commands in a vanilla Magento 2.3.3 EE and got no errors.
We will drop support for Magento 2.2 with end of year (in two days).

I close that ticket. If the error still occures, please re-open it.

**Closed by cmuench** 2019-12-29 14:52 UTC
