### ISSUE TITLE
sales_order_status is stripped out of database when using @development group breaking orders on Magento 2

### ISSUE THREAD

**Issue by JamesonNetworks** [netz98/n98-magerun2#239] opened 2016-09-14 20:39 UTC
When we create database dumps using the following command:

n98-magerun2 db:dump --strip="@development"

the sales_order_status* tables are being dropped. This breaks Magento 2 ordering, which relies on those status tables.

**Comment by tkn98** [comment] 2016-09-15 06:36
aren't these part with create commands in the dump file?

**Comment by valguss** [comment] 2016-10-17 14:04
Just had this on our site as well.
Step to reproduce:
1: dump out the database without any sales etc
~~~
n98-magerun2 db:dump --stripped="@development" 
~~~
2: Now import the database and you'll see that the sales_order_status* tables are now empty. Magento now has no record of any statuses that it can use in the system.

Here's the affected lines from n98-magerun2/config.yaml:
~~~
      - id: sales
        description: Sales data (orders, invoices, creditmemos etc)
        tables: sales_order* sales_recurring_* sales_refunded_* sales_payment_* enterprise_sales_* enterprise_customer_sales_*
~~~

The only table from sales_order_status* that should be cleaned is: sales_order_status_history

Thanks

Tom

**Comment by ktomk** [comment] 2016-10-17 15:37
Then the culprit is `sales_order*`. For review could you provide a listing of all tables matching in that pattern, e.g. `SHOW TABLES LIKE 'sales_order%';`? Just asking for better review.

For example on my end:

~~~
$ bin/n98-magerun2 db:query "SHOW TABLES LIKE 'sales_order%';"
Tables_in_magento_magerun2_test (sales_order%)
sales_order
sales_order_address
sales_order_aggregated_created
sales_order_aggregated_updated
sales_order_grid
sales_order_item
sales_order_payment
sales_order_status
sales_order_status_history
sales_order_status_label
sales_order_status_state
sales_order_tax
sales_order_tax_item
~~~

**Comment by valguss** [comment] 2016-10-17 15:40
Here we go:

~~~
sales_order
sales_order_address
sales_order_aggregated_created
sales_order_aggregated_updated
sales_order_grid
sales_order_item
sales_order_payment
sales_order_status
sales_order_status_history
sales_order_status_label
sales_order_status_state
sales_order_tax
sales_order_tax_item
~~~

Looks like we match.

**Comment by ktomk** [comment] 2016-10-17 15:56
So when I get it right we can empty everything from that list *but* `sales_order_status` as this is a reference table for statuses like *canceled* or *complete*.

**Comment by valguss** [comment] 2016-10-17 16:01
I think you should also not be emptying:
~~~
sales_order_status_state
sales_order_status_label
~~~

These contain frontend labels for the order statuses and the actual internal order state associated with each order status.

~~~
sales_order_status_history
~~~
this appears to contain comments on the order and order status updates for the order, so appears safe to truncate.

**Comment by ktomk** [comment] 2016-10-19 16:26
We believe that the bug reported is fixed in the development version. It can be upgraded to it using the `self-update` command with the `--unstable` switch.

**Closed by ktomk** 2016-10-19 16:26 UTC
Labels: bug

**Comment by valguss** [comment] 2016-10-24 10:20
Sorry for being awhile. That appears to be working fine for me. Thanks

**Comment by tkn98** [comment] 2016-10-24 11:16
No problem and thanks again.
