### ISSUE TITLE
Installation Script not found

### ISSUE THREAD

**Issue by julienvb** [netz98/n98-magerun2#156] opened 2015-12-02 22:14 UTC
Hi,

When running a clean install "n98-magerun2.phar install", the installation halts and throws an error:[RuntimeException]                  
Installation script was not found.  

![screen shot 2015-12-02 at 23 12 06](https://cloud.githubusercontent.com/assets/12121188/11545894/38ff9882-994a-11e5-9d25-71e4f395ddc7.jpg)

Any ideas how to resolve this issue?

Thanks!

**Comment by tkn98** [comment] 2015-12-03 08:24
I think the error message could be made more distinct. For example right now from the message magerun reports it is not clear to me whether or not this is an error from within magerun or the magento 2 install command itself that is invoked behind the scenes.

That said, it could be that this is a magento installer problem. Please try the manual install and report back if it works. Compare with #155 in which the cause of an installer problem is caused from magento 2 as well. If you can provide more information to that regard would be great!

**Comment by julienvb** [comment] 2015-12-03 10:53
Hi,

Please find attached a verbose report of running n98-magerun2 from the command line.
Let me know if this helps identifying the problem.

[log_n98.pdf](https://github.com/netz98/n98-magerun2/files/50703/log_n98.pdf)

Thanks!

**Comment by tkn98** [comment] 2015-12-03 14:55
That is the authentication required problem:

>  [Composer\Downloader\TransportException]
 The 'https://repo.magento.com/packages.json' URL required
authentication.
 You must be using the interactive console to authenticate 

(from the PDF)

I can confirm your report is a duplicate of #155 now.

**Closed by tkn98** 2015-12-03 14:55 UTC

**Comment by cmuench** [comment] 2015-12-04 16:48
@julienvb Please try develop version. We added a check for not set authentication.

`n98-magerun2.phar self-update --unstable`

**Comment by WouterSteen** [comment] 2016-01-14 08:00
When you do a n98magerun2 install for the first time, the installer asks to input your public and private key (from magentocommerce.com) to store it in auth.json in your composer directory.

If the installation fails on authentication, please check auth.json in your composer dir and check if the public and private key are correct. 
You have to have a key here:
https://www.magentocommerce.com/magento-connect/customerdata/secureKeys/list/

**Comment by tkn98** [comment] 2016-01-14 08:32
We should/could add a precondition check. I've seen M2EE projects fail that are under version control themseleves if the credentials aren't in place *before* the `composer install` command.
